jenkins:
  controller:
    additionalPlugins:
      - job-dsl:1.77
      - permissive-script-security:0.7
      - github-oauth:0.39
      - google-oauth-plugin:1.0.6

    javaOpts: '-Dpermissive-script-security.enabled=true'

    JCasC:
      defaultConfig: true
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: "Configured as code"

        job-config: |
          jobs:
            - script: >
                folder('python')
            - script: >
                pipelineJob('python/default-agent') {
                  definition {
                    cps {
                      script("""\
                      pipeline {
                        agent {
                          kubernetes {
                            yaml '''
                              apiVersion: v1
                              kind: Pod
                              metadata:
                                labels:
                                  purpose: jenkins-agent
                              spec:
                                containers:
                                - name: postgres
                                  image: postgres:latest
                                  command:
                                  - cat
                                  tty: true
                            '''
                          }
                        }
                        stages {
                          stage('Test it out') {
                            steps {
                              container('postgres') {
                                sh 'pwd'
                              }
                            }
                          }
                        }
                      }
                      """.stripIndent())
                      sandbox()
                    }
                  }
                }

